spring:
    profiles: dev
    application:
        name: microservice-almi-portal
    messages:
        basename: i18n/messages
        encoding: UTF-8
        cache-duration: 1s
    cloud:
        service-registry:
            auto-registration:
                enabled: true
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        enabled: true
        mode: HTML5
        encoding: UTF-8
        servlet:
            content-type: text/html
        cache: false

server:
    port: 8000
    
eureka:
    instance:
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://almi:almi@localhost:8761/eureka/
            