spring:
    application:
        name: microservice-almi-eureka
    security:
        user:
            name: almi
            password: almi         

server:
    port: 8761

eureka:
    instance:
        hostname: localhost
        prefer-ip-address: true

    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://almi:almi@localhost:${server.port}/eureka/